#!/bin/bash

function replace_ip() {
    local file="$1"
    local ip="$2"
    if [ -f "$file" ]; then
        sed -i "s/192\.168\.[0-9]\{1,3\}/${ip}/g" "/root/$file"
        echo "已经成功修改 $file 文件"
    elif [ ! -f "$file" ]; then
        echo "$file 文件不存在，开始下载"
        curl -fsSL "http://gh.zxi7.cn/https://raw.githubusercontent.com/YoYulyvW/tese/master/${file}" -o "/root/$file"
        if [ -f "$file" ]; then
            sed -i "s/192\.168\.[0-9]\{1,3\}/${ip}/g" "/root/$file"
            echo "已经成功修改 $file 文件"
        fi
    fi
}

# 获取用户输入的IP地址
read -p "请输入要修改的IP地址(前3位) [默认为192.168.1.240]: " ip_addr

if [ -n "$ip_addr" ]; then
    if [[ "$ip_addr" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        ip_addr=$(echo "$ip_addr" | cut -d "." -f 1-3)
    else
        echo "输入的IP地址不合法，使用默认值！"
        ip_addr="192.168.1.240"
    fi
else
    ip_addr="192.168.1.240"
fi

# 查找并替换openvpn-install.sh文件中的IP地址
replace_ip "openvpn-install.sh" "$ip_addr"

# 查找并替换openvpn-install-v6.sh文件中的IP地址
replace_ip "openvpn-install-v6.sh" "$ip_addr"

echo "已经修改ip为:${ip_addr}.x"

if dpkg -l docker-ce | grep -q "^ii"; then
    echo "Docker已安装"
else
    echo "Docker未安装，开始安装"
    curl -sSL https://get.daocloud.io/docker | sh
fi
