#!/bin/bash
# -*- coding: UTF-8 -*-

# 判断系统是否为Debian/Ubuntu/Armbian
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [ "$ID" = "debian" ] || [ "$ID" = "ubuntu" ] || [ "$ID" = "armbian" ]; then
        echo "检测到系统: $PRETTY_NAME"
        
        # 备份原有源列表
        echo "正在备份原有源列表..."
        cp /etc/apt/sources.list /etc/apt/sources.list.bak
        
        # 根据系统版本设置中科大源
        if [ "$ID" = "debian" ]; then
            echo "正在设置Debian中科大源..."
            cat > /etc/apt/sources.list <<EOF
deb https://mirrors.ustc.edu.cn/debian/ $VERSION_CODENAME main contrib non-free
deb https://mirrors.ustc.edu.cn/debian/ $VERSION_CODENAME-updates main contrib non-free
deb https://mirrors.ustc.edu.cn/debian/ $VERSION_CODENAME-backports main contrib non-free
deb https://mirrors.ustc.edu.cn/debian-security/ $VERSION_CODENAME-security main contrib non-free
EOF
        else
            echo "正在设置Ubuntu/Armbian中科大源..."
            cat > /etc/apt/sources.list <<EOF
deb https://mirrors.ustc.edu.cn/ubuntu/ $VERSION_CODENAME main restricted universe multiverse
deb https://mirrors.ustc.edu.cn/ubuntu/ $VERSION_CODENAME-updates main restricted universe multiverse
deb https://mirrors.ustc.edu.cn/ubuntu/ $VERSION_CODENAME-backports main restricted universe multiverse
deb https://mirrors.ustc.edu.cn/ubuntu/ $VERSION_CODENAME-security main restricted universe multiverse
EOF
        fi
        
        echo "源已成功更改为中科大镜像源"
        echo "正在更新软件包列表..."
        apt update
    else
        echo "错误：此脚本仅适用于Debian/Ubuntu/Armbian系统"
        exit 1
    fi
else
    echo "错误：无法确定操作系统类型"
    exit 1
fi

apt install ntp
# 修改系统时间 时区 
cat <<EOT > /etc/systemd/system/ntp-sync.service
[Unit]
Description=NTP Synchronization
After=network.target

[Service]
ExecStart=/usr/sbin/ntpd -g -u ntp:ntp -p /var/run/ntpd.pid
Restart=always

[Install]
WantedBy=multi-user.target
EOT
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
systemctl enable ntp-sync.service && systemctl start ntp-sync.service

function replace_ip() {
    local file="$1"
    local ip="$2"
    local file_path="/root/${file}"

    if [ -f "$file_path" ]; then
        echo "修改 $file 文件 ..."
    elif [ ! -f "$file_path" ]; then
        echo "$file 文件不存在，开始下载 ..."
        curl -sSL "https://git.lyvw.top:4433/https://raw.githubusercontent.com/YoYulyvW/tese/master/${file}" -o "$file_path"
    fi

    if ! grep -q "^net.ipv4.ip_forward=1$" /etc/sysctl.conf; then
        sed -i "s/^#net.ipv4.ip_forward.*/net.ipv4.ip_forward=1/g" /etc/sysctl.conf
        sysctl -q -p
        echo "设置 net.ipv4.ip_forward=1"
    fi

    sed -i "s/192\.168\.[0-9]\{1,3\}/${ip}/g" "$file_path"
    sed -i 's|https://github.com|https://git.lyvw.top:4433/https://github.com|g' "$file_path"
    sed -i 's|v3.1.4/EasyRSA-3.1.4.tgz|v3.2.0/EasyRSA-3.2.0.tgz|g' "$file_path"
    echo "已经成功修改 $file 文件"
    echo
}

# 获取用户输入的IP地址
echo 
echo "脚本内默认为192.168.254.0/24"
echo "请输入要修改的IP地址(前3位)例:192.168.250"
read -p " [留空回车使用默认值]: " ip_addr

if [ -n "$ip_addr" ]; then
    if [[ "$ip_addr" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        ip_addr=$(echo "$ip_addr" | cut -d "." -f 1-3)
    else
        echo "输入的IP地址不合法，使用默认值！"
        ip_addr="192.168.254"
    fi
else
    ip_addr="192.168.254"
fi

# 查找并替换openvpn-install.sh文件中的IP地址
replace_ip "openvpn-install.sh" "$ip_addr"

# 查找并替换openvpn-install-v6.sh文件中的IP地址
replace_ip "openvpn-install-v6.sh" "$ip_addr"

#echo "已经修改ip为:${ip_addr}.x"

if dpkg -l docker-ce | grep -q "^ii"; then
    echo "Docker已安装"
else
    echo "Docker未安装，开始安装"
    curl -sSL https://git.lyvw.top:4433/https://raw.githubusercontent.com/YoYulyvW/tese/master/get-docker | sh
fi

echo
